document.addEventListener('DOMContentLoaded', () => {
    // Smooth scrolling for navigation links
    document.querySelectorAll('nav a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();

            const targetId = this.getAttribute('href');
            const targetElement = document.querySelector(targetId);

            if (targetElement) {
                targetElement.scrollIntoView({
                    behavior: 'smooth'
                });
            }
        });
    });

    // Dynamic gallery rendering: try to load `images/gallery.json` (generated by scripts/generate-gallery.js)
    const galleryGrid = document.getElementById('gallery-grid');
    async function loadGallery() {
        if (!galleryGrid) return;
        let gallery = null;
        try {
            const res = await fetch('images/gallery.json', { cache: 'no-store' });
            if (res.ok) gallery = await res.json();
        } catch (e) {
            console.warn('Could not load images/gallery.json, falling back to built-in list', e);
        }

        // Fallback list (useful if gallery.json isn't generated yet)
        const fallback = [
            'womanlargebraids.jpeg',
            'braidsexample.jpeg',
            'braidswithbeedswomanexample.jpeg',
            'cornrowsandbraidshybrid.jpeg',
            'cornrowsandbraidshybrid2.jpeg',
            'womancombinghair.jpeg',
            'womanwashinghairshampoo.jpeg',
            'womanwithdarkbrownbraids.jpeg',
            '2womanhuggingeachotherwithcornrows.jpeg',
            'jackie-sahsoclean.jpeg',
            'auntiejackie-stransform.jpeg',
            'whatsapp-image-2025-11-07-at-18.58.31.jpeg'
        ];

        const images = Array.isArray(gallery) && gallery.length ? gallery : fallback;

        images.forEach(filename => {
            const wrapper = document.createElement('div');
            wrapper.className = 'gallery-item';

            const img = document.createElement('img');
            img.src = `images/${filename}`;
            img.alt = 'Braided hairstyle';
            img.loading = 'lazy';

            wrapper.appendChild(img);
            galleryGrid.appendChild(wrapper);
        });
    }

        loadGallery();

        // set current year in footer
        const yearEl = document.getElementById('year');
        if (yearEl) yearEl.textContent = new Date().getFullYear();

        // (Removed directional press handlers to keep buttons simple and reliable)
});

// Inline expansion for service cards (click to expand details)
(function () {
    const cards = document.querySelectorAll('.service-card');
    if (!cards || !cards.length) return;

    cards.forEach(card => {
        // prepare expanded container
        const detailsText = card.getAttribute('data-details') || '';
        const metaText = card.querySelector('.service-meta') ? card.querySelector('.service-meta').textContent : '';

        const expanded = document.createElement('div');
        expanded.className = 'service-expanded';
        expanded.innerHTML = `
            <div class="expanded-inner">
                <p class="expanded-desc">${detailsText}</p>
                <div class="expanded-meta">${metaText}</div>
                <div class="expanded-actions">
                    <button class="book-button" type="button">Book</button>
                    <button class="collapse-button" type="button" aria-label="Close details">Close</button>
                </div>
            </div>
        `;

        card.appendChild(expanded);
        card.setAttribute('aria-expanded', 'false');

        function open() {
            // collapse any other expanded cards
            document.querySelectorAll('.service-card.expanded').forEach(other => {
                if (other === card) return;
                other.classList.remove('expanded');
                other.setAttribute('aria-expanded', 'false');
                const otherExpanded = other.querySelector('.service-expanded');
                if (otherExpanded) otherExpanded.style.display = 'none';
            });

            card.classList.add('expanded');
            card.setAttribute('aria-expanded', 'true');
            expanded.style.display = 'block';
            // scroll into view a bit
            card.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }

        function close() {
            card.classList.remove('expanded');
            card.setAttribute('aria-expanded', 'false');
            expanded.style.display = 'none';
        }

        // click handler: toggle expansion unless clicking book link
        card.addEventListener('click', (e) => {
            if (e.target.closest('.book-button') || e.target.classList.contains('collapse-button')) return;
            const isExpanded = card.classList.contains('expanded');
            if (isExpanded) close(); else open();
        });

        // button handler to close
        expanded.querySelector('.collapse-button').addEventListener('click', (e) => {
            e.stopPropagation();
            close();
        });

        // keyboard support
        card.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                const isExpanded = card.classList.contains('expanded');
                if (isExpanded) close(); else open();
            }
            if (e.key === 'Escape' && card.classList.contains('expanded')) {
                close();
            }
        });

        // hide expanded by default
        expanded.style.display = 'none';
    });
})();

// Booking modal behavior: open form and redirect to WhatsApp with prefilled message
document.addEventListener('DOMContentLoaded', function () {
    const bookingModal = document.getElementById('booking-modal');
    const bookingForm = document.getElementById('booking-form');
    if (!bookingModal || !bookingForm) return;

    const bookingService = document.getElementById('booking-service');
    const nameInput = document.getElementById('booking-name');
    const phoneInput = document.getElementById('booking-phone');
    const datetimeInput = document.getElementById('booking-datetime');
    const notesInput = document.getElementById('booking-notes');
    const errorP = document.getElementById('booking-error');

    function openBooking(service) {
        bookingService.value = service || '';
        nameInput.value = '';
        phoneInput.value = '';
        datetimeInput.value = '';
        notesInput.value = '';
        errorP.style.display = 'none';
        bookingModal.classList.add('show');
        bookingModal.setAttribute('aria-hidden', 'false');
    }

    function closeBooking() {
        bookingModal.classList.remove('show');
        bookingModal.setAttribute('aria-hidden', 'true');
    }

    // open modal when clicking any .book-button inside a service card
    document.addEventListener('click', (e) => {
        const btn = e.target.closest && e.target.closest('.book-button');
        if (!btn) return;
        // only handle book clicks that are inside a service card (leave header/footer anchors alone)
        const card = btn.closest('.service-card');
        if (!card) return;
        e.preventDefault();
        const service = card.querySelector('.service-title') ? card.querySelector('.service-title').textContent.trim() : '';
        openBooking(service);
    });

    // Simple directional press indicator: set data-press to left/right/center on pointerdown, clear on up
    (function simplePressDirection() {
        function onPointerDown(e) {
            const btn = e.target.closest && e.target.closest('.book-button');
            if (!btn || e.isPrimary === false) return;
            const r = btn.getBoundingClientRect();
            const x = e.clientX - r.left;
            const half = r.width / 2;
            if (x < half * 0.6) btn.setAttribute('data-press', 'left');
            else if (x > half * 1.4) btn.setAttribute('data-press', 'right');
            else btn.setAttribute('data-press', 'center');
        }
        function clearPress(e) {
            const btn = (e && e.target && e.target.closest) ? e.target.closest('.book-button') : null;
            // if pointerup fired on a different element, clear all book buttons
            if (!btn) {
                document.querySelectorAll('.book-button[data-press]').forEach(b => b.removeAttribute('data-press'));
                return;
            }
            btn.removeAttribute('data-press');
        }

        document.addEventListener('pointerdown', onPointerDown, { passive: true });
        document.addEventListener('pointerup', clearPress);
        document.addEventListener('pointercancel', clearPress);
        document.addEventListener('pointerleave', clearPress);

        // keyboard support: show center press on keydown and clear on keyup
        document.addEventListener('keydown', (ev) => {
            if (!(ev.key === ' ' || ev.key === 'Enter')) return;
            const el = document.activeElement;
            if (el && el.classList && el.classList.contains('book-button')) el.setAttribute('data-press', 'center');
        });
        document.addEventListener('keyup', (ev) => {
            if (!(ev.key === ' ' || ev.key === 'Enter')) return;
            const el = document.activeElement;
            if (el && el.classList && el.classList.contains('book-button')) el.removeAttribute('data-press');
        });
    })();

    // close handlers
    bookingModal.querySelectorAll('[data-booking-close]').forEach(btn => btn.addEventListener('click', closeBooking));

    // submit: validate and show confirmation preview before redirecting to WhatsApp
    bookingForm.addEventListener('submit', (e) => {
        e.preventDefault();
        const name = nameInput.value.trim();
        const phone = phoneInput.value.trim();
        const email = (document.getElementById('booking-email') || {}).value.trim();
        const datetime = datetimeInput.value.trim();
        const notes = notesInput.value.trim();
        const service = bookingService.value.trim();
        const consent = !!document.getElementById('booking-consent').checked;

        if (!name) { errorP.textContent = 'Please enter your name.'; errorP.style.display = 'block'; return; }
        if (!phone) { errorP.textContent = 'Please enter your WhatsApp phone number.'; errorP.style.display = 'block'; return; }
        if (!consent) { errorP.textContent = 'Please confirm you consent to be contacted via WhatsApp.'; errorP.style.display = 'block'; return; }

        // normalize phone to digits (wa.me requires no + or spaces)
        const phoneDigits = phone.replace(/[^0-9]/g, '');
        if (phoneDigits.length < 9) { errorP.textContent = 'Please enter a valid phone number.'; errorP.style.display = 'block'; return; }

        // build message preview
        let msg = `Booking request from website\n`;
        if (service) msg += `Service: ${service}\n`;
        msg += `Name: ${name}\n`;
        if (email) msg += `Email: ${email}\n`;
        msg += `Phone: ${phone}\n`;
        if (datetime) msg += `Preferred: ${datetime}\n`;
        if (notes) msg += `Notes: ${notes}\n`;

        // show preview area and ask for confirmation before opening WhatsApp
        const preview = document.getElementById('booking-preview');
        const previewContent = document.getElementById('booking-preview-content');
        const bookingBack = document.getElementById('booking-back');
        const bookingConfirm = document.getElementById('booking-confirm');
        previewContent.textContent = msg;
        // hide form, show preview
        bookingForm.style.display = 'none';
        preview.style.display = 'block';

        // on confirm, open WhatsApp
        function doConfirm() {
            const businessNumber = '27684535380';
            const url = `https://wa.me/${businessNumber}?text=${encodeURIComponent(msg)}`;
            window.open(url, '_blank');
            // cleanup
            preview.style.display = 'none';
            bookingForm.style.display = '';
            closeBooking();
            bookingConfirm.removeEventListener('click', doConfirm);
            bookingBack.removeEventListener('click', doBack);
        }

        function doBack() {
            preview.style.display = 'none';
            bookingForm.style.display = '';
            bookingConfirm.removeEventListener('click', doConfirm);
            bookingBack.removeEventListener('click', doBack);
        }

        bookingConfirm.addEventListener('click', doConfirm);
        bookingBack.addEventListener('click', doBack);
    });
});